#! /bin/sh
# /etc/init.d/blah
#

### BEGIN INIT INFO
# Provides:          fayezscript
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       init script to launch on bootup
### END INIT INFO

# Run at boot time
# init script initilaises start flag straight away so it will come to this function and check.
checkIfDaemonExists()
{
  if [ -f /tmp/daemonPID.txt ]
  then
    echo "I can't start new Daemon, one already running"
    #1 = non zero means failure
    return 1
  else
    echo "I can create a new daemon"
    #0 = no failure (basically true)
    return 0
  fi
}


# Carry out specific functions when asked to by the system
case "$1" in
  start)
    if checkIfDaemonExists; 
      then
        ./home/fayezrahman/Desktop/CA1/SystemSoftwareCA1/myprog
      else
        echo "I can't start new Daemon, one already running"
    fi
    ;;
  stop)
    echo "Stopping daemon"
    killall myprog
    rm /tmp/daemonPID.txt
    ;;
  backup)
    echo "Forcing backup"
    ./home/fayezrahman/Desktop/CA1/SystemSoftwareCA1/myprog backup
    ;;
  *)
    echo "Usage: /etc/init.d/blah {start|stop|backup}"
    exit 1
    ;;
esac

exit 0
